name: Static Code Analysis On Bank App Backend


on: 
  push: 
    branches:
      - SeOps


jobs:
  Dependency-Check:
    name: OWASP-Dependency-Check
    runs-on: ubuntu-latest
    environment: SecOps

    steps: 
      - name: Checkout repository.
        uses: actions/checkout@v3
        with:
          repository: digitalwitchdemo/main_bank_app_backend
          ref: SeOps

      - name: SetUp JDK 1.8 
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '21'


      - name: Dependency check lib installation
        run: | 
             mvn org.owasp:dependency-check-maven:check -DnvdApiKey=6b19ac9f-56c6-4511-8db6-2c3f5dd85585
             ls -la ./target
             cat ./target/dependency-check-report.csv

        # Upload JaCoCo HTML report as artifact
      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco


  #     - name: Uploading to DefectDojo
        # run: | 
        #      chmod +x dependency-check-upload.sh
        #      sh dependency-check-upload.sh
        


















