name: Static Code Analysis On Dependency Check analysis

on: 
  push: 
    branches:
      - SeOps

jobs: 
  Dependency-Check:
    name: OWASP-Dependency-Check
    runs-on: ubuntu-latest
    environment: SecOps

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: digitalwitchdemo/main_bank_app_backend
          ref: SeOps

      - name: SetUp JDK 1.8 
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '21'
      - run: java HelloWorldApp.java


      - name: Dependency check lib installation
        run: | 
             mvn org.owasp:dependency-check-maven:check

             
  # Sonar-Scan:
  #   name: Sonar-Scan
  #   runs-on: ubuntu-latest
  #   environment: SecOps

  #   steps:
  #     - name: Checkout
  #       uses: action/checkout@v3  
