name: Static Code Analysis and Dependency Check analysis.

on:
  push:
    branches:
      - main

jobs:
  OWASP-ependency-Check:
    name: Dependency-Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SetUp JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '21'


      - name: Dependency check lib installation
        run: | 
             mvn org.owasp:dependency-check-maven:check -DnvdApiKey=${{ secrets.NVD_API_KEY_01 }}
