name: Static Code Analysis and Dependency Check analysis.

on:
  push:
    branches:
      - main

jobs:
  # OWASP-ependency-Check:
  #   name: Dependency-Check
  #   runs-on: ubuntu-latest
    
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: SetUp JDK 21
  #       uses: actions/setup-java@v4
  #       with:
  #         distribution: 'zulu' # See 'Supported distributions' for available options
  #         java-version: '21'


  #     - name: Dependency check lib installation
  #       run: | 
  #            mvn org.owasp:dependency-check-maven:check -DnvdApiKey=${{ secrets.NVD_API_KEY_01 }}
  #            ls -la ./target

  #            cat ./target/dependency-check-report.csv
             

  #     - name: Upload to DefectDojo
  #       run: |
  #          chmod +x  dependencycheck-defectdojoupload.sh
  #          sh ./dependencycheck-defectdojoupload.sh

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          
      - name: maven clean verify  
        run: mvn clean verify -DnvdApiKey=${{ secrets.NVD_API_KEY_01 }}

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=cloud-solution-us
            -Dsonar.projectKey=bank-app-backend
            -Dsonar.java.binaries=target/classes
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        
             
