name: Static Code Analysis On Bank App Backend


on: 
  push: 
    branches:
      - SeOps


jobs: 
  # Dependency-Check:
  #   name: OWASP-Dependency-Check
  #   runs-on: ubuntu-latest
  #   environment: SecOps

  #   steps: 
  #     - name: Checkout repository
  #       uses: actions/checkout@v3
  #       with:
  #         repository: digitalwitchdemo/main_bank_app_backend
  #         ref: SeOps

  #     - name: SetUp JDK 1.8 
  #       uses: actions/setup-java@v4
  #       with:
  #         distribution: 'zulu' # See 'Supported distributions' for available options
  #         java-version: '21'


  #     - name: Dependency check lib installation
  #       run: | 
  #            mvn org.owasp:dependency-check-maven:check -DnvdApiKey=${{ secrets.NVD_API_KEY }}
  #            ls -la ./target
  #            cat ./target/dependency-check-report.csv


  #     - name: Uploading to DefectDojo
        # run: | 
        #      chmod +x dependency-check-upload.sh
        #      sh dependency-check-upload.sh
        


















  dockerfile-compliance-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run OPA Rego Tests
        uses: masterpointio/github-action-opa-rego-test@main
        with:
          path: ./opa
          test_mode: directory # Whether to test the Rego by directory (e.g. opa test ./) or by individual files (e.g. opa test a_test.rego a.rego). Options of `directory` or `file`.
          report_untested_files: true