name: Static Code Analysis On Bank App Backend


on: 
  push: 
    branches:
      - SeOps


jobs: 
  # Dependency-Check:
  #   name: OWASP-Dependency-Check
  #   runs-on: ubuntu-latest
  #   environment: SecOps

  #   steps: 
  #     - name: Checkout repository
  #       uses: actions/checkout@v3
  #       with:
  #         repository: digitalwitchdemo/main_bank_app_backend
  #         ref: SeOps

  #     - name: SetUp JDK 1.8 
  #       uses: actions/setup-java@v4
  #       with:
  #         distribution: 'zulu' # See 'Supported distributions' for available options
  #         java-version: '21'


  #     - name: Dependency check lib installation
  #       run: | 
  #            mvn org.owasp:dependency-check-maven:check -DnvdApiKey=${{ secrets.NVD_API_KEY }}
  #            ls -la ./target
  #            cat ./target/dependency-check-report.csv


  #     - name: Uploading to DefectDojo
        # run: | 
        #      chmod +x dependency-check-upload.sh
        #      sh dependency-check-upload.sh
        


















  dockerfile-compliance-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Generate Dockerfile JSON.
        run: |
          bash opa/dockerfile-to-json.sh Dockerfile > ${GITHUB_WORKSPACE}/opa/dockerfile.json
          ls -la ${GITHUB_WORKSPACE}/opa

      - name: Run OPA Policy Check
        run: |
          sudo apt install unzip wget -y
          wget https://github.com/open-policy-agent/opa/archive/refs/tags/v1.7.1.zip
          unzip v1.7.1.zip
          mv opa-1.7.1 opa
          chmod 755 ./opa
          cp dockerfile-to-json.sh opa/
          cp d
          # sudo mv ./opa/opa /usr/local/bin/opa
          # ls -la /usr/local/bin/opa
          echo "Running OPA policy check on Dockerfile"
          opa version
          dockerfile-to-json.sh Dockerfile > ${GITHUB_WORKSPACE}/dockerfile.json
          # opa eval --data ./opa/policy.rego --input ${GITHUB_WORKSPACE}/

          # #./opa run --server --set=decision_logs.console=true ./opa/policy.rego ${GITHUB_WORKSPACE}/opa/dockerfile.json


